import Head from "next/head";
import Image from "next/image";
import { Contact } from "../components/contact/contact";
import { CopyrightFooter } from "../components/copyrightFooter";
import { FooterLinks } from "../components/footerLinks";
import { Introduction } from "../components/introduction/introduction";
import { NavLinksContainer } from "../components/navbar/navLinksContainer";
import { ProfileImage } from "../components/profileImage";
import { Skills } from "../components/skills/skills";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Akash Pinnani</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <NavLinksContainer />
        <div className={styles.introductionWrapper}>
          <div className={styles.profileImageWrapper}>
            <ProfileImage />
            {/* <FooterLinks /> */}
          </div>
          <Introduction />
        </div>
      </div>
      <div className={styles.container} id="skills">
        <Skills />
      </div>

      <div className={styles.container} id="contact">
        <Contact />
      </div>
      <CopyrightFooter/>
    </>
  );
}
